server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KillerNoMercy/neworder.git
          search-paths: /respo
          username: KillerNoMercy
          password: zsl317309
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
