server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
